### ISSUE TITLE
Extending the approach to other model architectures and languages

### ISSUE THREAD

**Issue by RibinMathewChalumattu** [zthang/Focus#1]
Hi,

Thanks for the great work. Is it possible to extend this approach to other model architectures, such as Mistral? I would also like to apply the hallucination detection for the German language. What would need to be modified to do so?

**Comment by zthang** [comment]
Thanks for your question, I will update the code for Mistral based models this weekend.

**Comment by zthang** [comment]
I have updated the code. In general, if you want to add a new type of LLM as the backbone, you need to modify the source code of modeling_{your model}.py in  transformer library and use utils/count_token_frequency.py to generate the idf file corresponding to the tokenizer used by the model.

If you have any other questions, please feel free to ask!
