### ISSUE TITLE
Q about running on multiple GPUs

### ISSUE THREAD

**Issue by 141forever** [zthang/Focus#2]
Hi, congratulate to your work!
I am now trying to run the following code.
python run_wikibiogpt3.py --model_path ausboss/llama-30b-supercot --low_cpu_mem_usage
Since it is a 30B model, so I need two GPUs. How can I write the code？

**Comment by zthang** [comment]
I think the code should run successfully on multiple GPUs, given that the device_map is set to "auto". Have you encountered any issues?

**Comment by 141forever** [comment]
I see it.
But I mean could I choose which GPU to use? For example, I wanna use GPU = 2,3,5,6 (In an 8 GPUs machine), what can I do?

**Comment by zthang** [comment]
Just add `os.environ["CUDA_VISIBLE_DEVICES"] = "2,3,5,6"` at the top of your code or use `CUDA_VISIBLE_DEVICES=2,3,5,6 python your_code.py` in the command line.

**Comment by 141forever** [comment]
I appreciate it a lot！
